<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <Version>1.0.8</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
